POST http://localhost:3003/confirm
Content-Type: application/json

{
    "name": "Sérvulo",
    "level": "1",
    "email": "servulo@gmail.com",
    "linkedin": "linkedin/servulo",
    "github": "github/servulo"
}

#######

GET http://localhost:3003/candidate
Content-Type: application/json


